property_label = {
    'havelegend': 'Enable legend',
    'legend.loc': 'Legend location',
    'legend.frameon': 'Enable legend frame',
    'legend.framealpha': 'Legend frame transparency',
    'legend.fontsize' : 'Legend font size',
    'legend.edgecolor': 'Legend edge color',
    'figure.figsize': 'Figure size',
    'lines.markersize': 'Marker size',
    'lines.linewidth': 'Line width',
    'font.size': 'Font size',
    'xlabel': 'Label for x-axis',
    'ylabel': 'Label for y-axis',
    'title': 'Title',
    'xlim': 'X-axis limits',
    'ylim': 'Y-axis limits',
    'xticks': 'X-axis ticks',
    'yticks': 'Y-axis ticks',
    'xscale': 'X-axis scale type',
    'yscale': 'Y-axis scale type',
    'snplot.color_dict': "Color Map Choose",
    'snplot.color_wheel': "Color Wheel"
}
