property_label = {
    'havelegend': 'Enable legend',
    'legend.loc': 'Legend location',
    'legend.frameon': 'Enable legend frame',
    'legend.framealpha': 'Legend frame transparency',
    'legend.fontsize' : 'Legend font size',
    'legend.edgecolor': 'Legend edge color',
    'figure.figsize': 'Figure size',
    'lines.markersize': 'Marker size',
    'lines.linewidth': 'Line width',
    'font.size': 'Font size',
    'xtick.major.pad': 'X-axis tick padding',
    'ytick.major.pad': 'Y-axis tick padding',
    'xlabel': 'Label for x-axis',
    'ylabel': 'Label for y-axis',
    'title': 'Title',
    'legend.title': 'Legend title',
    'legend.title_fontsize': 'Legend title font size',
    'markerfirst': 'Marker first in legend',
    'xlim': 'X-axis limits',
    'ylim': 'Y-axis limits',
    'xticks': 'X-axis ticks',
    'yticks': 'Y-axis ticks',
    'xscale': 'X-axis scale type',
    'yscale': 'Y-axis scale type',
    'snplot.color_dict': "Color Map Choose",
    'snplot.color_wheel': "Color Wheel",
    'snplot.scatter.fill': 'Enable scatter fill',
    'snplot.outercontourwidth': 'Outer contour width',
    'snplot.contour_x_label': 'Contour x-axis label',
    'snplot.contour_y_label': 'Contour y-axis label',
    'snplot.contour_resolution': 'Contour resolution',
    'snplot.contour_axis_on': 'Enable contour axis',
    'snplot.contour.cmap': 'Contour color map'
}
